cocktail/config/routes.rb
Rails.application.routes.draw do
  resources :drinks
  resources :ingredients
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/sign_in', to: 'sessions#sign_in'
  post '/sign_in', to: 'sessions#create'
end

cocktail/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cocktail/app/models/disliked_item.rb
class DislikedItem < ApplicationRecord
    belongs_to :user 
    belongs_to :drink
end

cocktail/app/models/drink.rb
class Drink < ApplicationRecord
    has_many :liked_items
    has_many :users, through: :liked_items
    has_many :disliked_items
    has_many :users, through: :disliked_items
    has_many :drink_ingredients
    has_many :ingredients, through: :drink_ingredients

    def self.fetch_id(name)
        Drink.all.find{ |drink| drink.name == name}.id
    end 

    def existing(name)
        Drink.all.each do |drink|
            if drink.name == name
                return true
            end
        end
        false
    end 
end

cocktail/app/models/drink_ingredient.rb
class DrinkIngredient < ApplicationRecord
    belongs_to :drink 
    belongs_to :ingredient
    
end

cocktail/app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :drink_ingredients
    has_many :drinks, through: :drink_ingredients

    def self.existing(newIngredient)
        Ingredient.all.each do |ingredient| 
            if ingredient.name == newIngredient
                return true
            end 
        end 
        false
    end 

    def self.fetch_id(ingredient)
        Ingredient.all.find{ |i| i.name == ingredient}.id
    end 
end

cocktail/app/models/liked_item.rb
class LikedItem < ApplicationRecord
    belongs_to :user
    belongs_to :drink

    def self.like(user_id, drink_id)
        byebug
        #@like = LikedItem.create(user_id, drink_id)
        puts @like
    end 
end

cocktail/app/models/user.rb
class User < ApplicationRecord
    has_many :liked_items
    has_many :drinks, through: :liked_items
    has_many :disliked_items
    has_many :drinks, through: :disliked_items
    has_secure_password
end

cocktail/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cocktail/app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

    def index 
        @drinks = Drink.all

    end 

    def show
        @drink = Drink.find(params[:id])
        
    end

end

cocktail/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

    def index 
        @ingredients = Ingredient.all

    end 

    def show
        @ingredient = Ingredient.find(params[:id])
    end
end

cocktail/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def sign_up

    end

    def sign_in
        @user = User.new
    end

    def create
        @user = User.find_by(email: params[:user][:email])
        if @user && @user.authenticate(params[:user][:password])
            session[:id] = @user.id
            byebug
            redirect_to "/users/#{session[:id]}"
        else
            flash[:error] = "Incorrect Email or Password"
            redirect_to '/sign_in'
        end
    end
    
end

cocktail/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticated?, only: [:show]

    def show
        @user = User.find(params[:id])
    end 

    def authenticated?
        if session[:id] != nil
            @user = User.find(session[:id]) 
        else
            redirect_to '/sign_in'
        end
    end 

    def new 
        @user = User.new
    end 

    def create 
        @user = User.new(user_params)
        #validate
        if !@user.valid?
            redirect_to new_user_path(@user)
        end 
        @user.save
        byebug
        redirect_to user_path(@user)
    end 

    private 

    def user_params
        params.require(:user).permit(:first_name, :last_name, :age, :email, :password)
    end 
end

cocktail/app/helpers/application_helper.rb
module ApplicationHelper
end

cocktail/app/helpers/drinks_helper.rb
module DrinksHelper
end

cocktail/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

cocktail/app/helpers/sessions_helper.rb
module SessionsHelper
end

cocktail/app/helpers/user_helper.rb
module UserHelper
end

cocktail/app/helpers/users_helper.rb
module UsersHelper
end

cocktail/app/views/drinks/index.html.erb
<!DOCTYPE html>
<html>
   <head>
      <% stylesheet_link_tag "drink_index" %>
      <h1 class=“head”>Drinks</h1>
   </head>
   <body>
      <% @drinks.each do | drink |%>
         <li class=“link”> <%= link_to drink.name, drink_path(drink)%> </li>
      <% end %>
   </body>
</html>

cocktail/app/views/drinks/show.html.erb
<!DOCTYPE html>
<html>
    <head>
        <% stylesheet_link_tag "drink_show"%>
        <h1 class><%= @drink.name%></h1>
    </head>
    <body>
        
        <%= @drink.instructions %><br>
        <%= @drink.category %><br>
        <%= @drink.glass%><br>
        <%= @drink.alcoholic%><br>
        <br>
        Ingredient:
            <% @drink.ingredients.each do | ingredient | %>
                <li> <%= link_to ingredient.name, ingredient_path(ingredient) %> </li>
            <% end %>

    </body>
</html>

cocktail/app/views/ingredients/index.html.erb
<!DOCTYPE html>
<html>
   <head>
      <% stylesheet_link_tag "ingredient_index" %>
      <h1 class=“head”>Ingredients</h1>
   </head>
   <body>
      <% @ingredients.each do | ingredient |%>
         <li class=“link”> <%= link_to ingredient.name, ingredient_path(ingredient)%> </li>
      <% end %>
   </body>
</html>

cocktail/app/views/ingredients/show.html.erb
<!DOCTYPE html>
<html>
    <head>
        <% stylesheet_link_tag "ingredient_show"%>
        <h1 class><%= @ingredient.name%></h1>
    </head>
    <body>
        
       Drinks:
            <% @ingredient.drinks.each do | drink | %>
                <li> <%= link_to drink.name, drink_path(drink) %> </li>
            <% end %>

    </body>
</html>

cocktail/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

cocktail/app/views/users/_form.html.erb
<%= form_with model: @user do |f|%>
    <%=f.label :first_name%><br>
    <%=f.text_field :first_name%><br>
    <%=f.label :last_name%><br>
    <%=f.text_field :last_name%><br>
    <%=f.label :age%><br>
    <%=f.text_field :age%><br>
    <%=f.label :email%><br>
    <%=f.text_field :email%><br>
    <%=f.label :password%><br>
    <%=f.text_field :password%><br>
    <%=f.submit%>
<% end %>

cocktail/app/views/users/new.html.erb
<%= render "form"%>

cocktail/app/views/users/show.html.erb
<!DOCTYPE html>
<html>
    <head>
        <% stylesheet_link_tag "user_show"%>
    </head>
    <body>
        <h1>Welcome <%=@user.first_name%></h1>
    </body>
</html>